//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using BJSYGameCore.UI;
    using BJSYGameCore.AutoCompo;
    using System;
    using UnityEngine;
    
    [AutoCompoAttribute(-3836)]
    public partial class SceneObject : UIObject
    {
        public void autoBind()
        {
            this._asRectTransform = this.GetComponent<RectTransform>();
        }
        private RectTransform _asRectTransform;
        public RectTransform asRectTransform
        {
            get
            {
                return this._asRectTransform;
            }
        }
    }
}
