//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using BJSYGameCore.UI;
    using BJSYGameCore.AutoCompo;
    using System;
    using UnityEngine;
    using UnityEngine.UI;
    
    [AutoCompoAttribute(19190)]
    public partial class AutoUI : UIObject
    {
        public void init()
        {
            this._asRect = this.transform.findByPath("./").GetComponent<RectTransform>();
            this._asAnimator = this.transform.findByPath("./").GetComponent<Animator>();
            this._returnButton = this.transform.findByPath("./ReturnButton").GetComponent<Button>();
            this._returnButton.onClick.AddListener(this.ReturnButtonClickCallback);
            this._nameText = this.transform.findByPath("./Name").GetComponent<Text>();
        }
        public void clear()
        {
            this._returnButton.onClick.RemoveListener(this.ReturnButtonClickCallback);
        }
        [SerializeField()]
        [AutoCompoAttribute(24390, "./")]
        private RectTransform _asRect;
        public RectTransform asRect
        {
            get
            {
                return this._asRect;
            }
        }
        [SerializeField()]
        [AutoCompoAttribute(24404, "./")]
        private Animator _asAnimator;
        public Animator asAnimator
        {
            get
            {
                return this._asAnimator;
            }
        }
        [SerializeField()]
        [AutoCompoAttribute(24420, "./ReturnButton")]
        private Button _returnButton;
        public Button returnButton
        {
            get
            {
                return this._returnButton;
            }
        }
        public event Action onReturnButtonClick;
        private void ReturnButtonClickCallback()
        {
            if ((this.onReturnButtonClick != null))
            {
                this.onReturnButtonClick();
            }
        }
        [SerializeField()]
        [AutoCompoAttribute(24412, "./Name")]
        private Text _nameText;
        public Text nameText
        {
            get
            {
                return this._nameText;
            }
        }
    }
}
