//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using UnityEngine;
    using UnityEngine.UI;
    using BJSYGameCore.AutoCompo;
    
    [AutoCompoAttribute(13812)]
    public partial class AutoUI : MonoBehaviour
    {
        public void autoBind()
        {
            this._asRectTransform = this.GetComponent<RectTransform>();
            this._asAnimator = this.GetComponent<Animator>();
            this._returnButton = this.transform.Find("return.Button").GetComponent<Button>();
            this._nameText = this.transform.Find("name.Text").GetComponent<Text>();
        }
        [SerializeField()]
        private RectTransform _asRectTransform;
        public RectTransform asRectTransform
        {
            get
            {
                return this._asRectTransform;
            }
        }
        [SerializeField()]
        private Animator _asAnimator;
        public Animator asAnimator
        {
            get
            {
                return this._asAnimator;
            }
        }
        [SerializeField()]
        private Button _returnButton;
        public Button returnButton
        {
            get
            {
                return this._returnButton;
            }
        }
        [SerializeField()]
        private Text _nameText;
        public Text nameText
        {
            get
            {
                return this._nameText;
            }
        }
    }
}
