//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests
{
    using BJSYGameCore.AutoCompo;
    using System;
    using UnityEngine.UI;

    public partial class AutoUI
    {
        public void autoInit()
        {
            this._returnButton = this.transform.Find(PATH_RETURNBUTTON).GetComponent<Button>();
            this._returnButton.onClick.AddListener(this.ReturnButtonClickCallback);
            this._nameText = this.transform.Find(PATH_NAMETEXT).GetComponent<Text>();
        }
        public void autoClear()
        {
            this._returnButton.onClick.RemoveListener(this.ReturnButtonClickCallback);
        }
        public Button _returnButton;
        public const string PATH_RETURNBUTTON = "ReturnButton";
        public Button returnButton
        {
            get
            {
                if ((this._returnButton == null))
                {
                    this._returnButton = this.transform.Find(PATH_RETURNBUTTON).GetComponent<Button>();
                }
                return this._returnButton;
            }
        }
        public event Action onReturnButtonClick;
        private void ReturnButtonClickCallback()
        {
            if ((this.onReturnButtonClick != null))
            {
                this.onReturnButtonClick();
            }
        }
        public Text _nameText;
        public const string PATH_NAMETEXT = "Name";
        public Text nameText
        {
            get
            {
                if ((this._nameText == null))
                {
                    this._nameText = this.transform.Find(PATH_NAMETEXT).GetComponent<Text>();
                }
                return this._nameText;
            }
        }
    }
}
